$ python manage.py test usuarios
Found 13 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.............
----------------------------------------------------------------------
Ran 13 tests in 7.386s

OK
Destroying test database for alias 'default'...
